spring:
  datasource:
    url: jdbc:mysql://47.106.237.143:3306/test?characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    maxActive: 30
    maxWait: 30000
    validationQuery: select 1
    testWhileIdle: true
    removeAbandoned: true
    filters: stat,wall #配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
  redis:
    host: 47.106.237.143
    port: 6379
    password:
  cache:
    type: redis
debug: false
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
# 显示mybatis执行的sql语句
logging:
  level:
    com:
      zhang:
        firsapplication: DEBUG
