spring:
  datasource:
    url: jdbc:mysql://192.168.2.111:3306/test?characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    type: com.alibaba.druid.pool.DruidDataSource
debug: false
mybatis:
  mapper-locations: classpath:mapper/*.xml
logging:
  level: trace