package com.zhang.firsapplication.dao;

import com.zhang.firsapplication.bean.UserPassword;
import com.zhang.firsapplication.bean.UserPasswordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserPasswordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Mon Jan 28 16:41:50 CST 2019
     */
    long countByExample(UserPasswordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Mon Jan 28 16:41:50 CST 2019
     */
    int deleteByExample(UserPasswordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Mon Jan 28 16:41:50 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Mon Jan 28 16:41:50 CST 2019
     */
    int insert(UserPassword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Mon Jan 28 16:41:50 CST 2019
     */
    int insertSelective(UserPassword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Mon Jan 28 16:41:50 CST 2019
     */
    List<UserPassword> selectByExample(UserPasswordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Mon Jan 28 16:41:50 CST 2019
     */
    UserPassword selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Mon Jan 28 16:41:50 CST 2019
     */
    int updateByExampleSelective(@Param("record") UserPassword record, @Param("example") UserPasswordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Mon Jan 28 16:41:50 CST 2019
     */
    int updateByExample(@Param("record") UserPassword record, @Param("example") UserPasswordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Mon Jan 28 16:41:50 CST 2019
     */
    int updateByPrimaryKeySelective(UserPassword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Mon Jan 28 16:41:50 CST 2019
     */
    int updateByPrimaryKey(UserPassword record);
}